services:
  - type: web
    name: kappa-tracker
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kappa-db
          property: connectionString

databases:
  - name: kappa-db
    databaseName: kappatracker
    plan: free
    region: oregon

